// views/RelatoriosView.tsx
import React, { useState, useMemo, useCallback } from 'react';
import { Billing, Customer, DebtPayment, Expense } from '../types';
import PageHeader from '../components/PageHeader';
import { PrinterIcon } from '../components/icons/PrinterIcon';

interface RelatoriosViewProps {
  customers: Customer[];
  billings: Billing[];
  expenses: Expense[];
  debtPayments: DebtPayment[];
}

// --- Sub-components (moved outside for performance and best practices) ---

interface InfoCardProps {
    title: string;
    children: React.ReactNode;
}
const InfoCard: React.FC<InfoCardProps> = React.memo(({ title, children }) => (
    <div className="bg-white dark:bg-slate-800 p-6 rounded-lg shadow-lg border border-slate-200 dark:border-slate-700 h-full flex flex-col">
        <h3 className="text-xl font-semibold text-slate-900 dark:text-white mb-4 border-b border-slate-200 dark:border-slate-700 pb-3">{title}</h3>
        <div className="flex-grow">
            <dl className="space-y-3">
                {children}
            </dl>
        </div>
    </div>
));

interface InfoRowProps {
    label: string;
    value: string;
    valueColor?: string;
}
const InfoRow: React.FC<InfoRowProps> = React.memo(({ label, value, valueColor = 'text-slate-700 dark:text-slate-300' }) => (
    <div className="flex justify-between items-baseline">
        <dt className="text-slate-500 dark:text-slate-400">{label}</dt>
        <dd className={`font-mono font-bold ${valueColor}`}>{value}</dd>
    </div>
));

// --- Main View Component ---

const RelatoriosView: React.FC<RelatoriosViewProps> = ({ customers, billings, expenses, debtPayments }) => {
  const getInitialDateRange = () => {
    const today = new Date();
    const firstDay = new Date(today.getFullYear(), today.getMonth(), 1);
    const lastDay = new Date(today.getFullYear(), today.getMonth() + 1, 0);
    return {
        start: firstDay.toISOString().split('T')[0],
        end: lastDay.toISOString().split('T')[0]
    };
  };

  const [dateRange, setDateRange] = useState(getInitialDateRange);

  const handleDateChange = useCallback((e: React.ChangeEvent<HTMLInputElement>) => {
    const { name, value } = e.target;
    setDateRange(prev => ({ ...prev, [name]: value }));
  }, []);

  const stats = useMemo(() => {
    const start = dateRange.start ? new Date(dateRange.start) : null;
    if (start) start.setHours(0, 0, 0, 0);

    const end = dateRange.end ? new Date(dateRange.end) : null;
    if (end) end.setHours(23, 59, 59, 999);
    
    const filterByDate = (itemDateStr: Date) => {
        const itemDate = new Date(itemDateStr);
        if (start && itemDate < start) return false;
        if (end && itemDate > end) return false;
        return true;
    };

    const periodBillings = billings.filter(b => filterByDate(b.settledAt));
    const periodDebtPayments = debtPayments.filter(p => filterByDate(p.paidAt));
    const periodExpenses = expenses.filter(e => filterByDate(e.date));
    
    // Filtered Billings
    const periodMesaBillings = periodBillings.filter(b => b.equipmentType === 'mesa');
    const periodJukeboxBillings = periodBillings.filter(b => b.equipmentType === 'jukebox');
    const periodGruaBillings = periodBillings.filter(b => b.equipmentType === 'grua');

    // Revenue by Equipment
    const revenueMesaDinheiro = periodMesaBillings.filter(b => b.paymentMethod === 'dinheiro').reduce((sum, b) => sum + b.valorTotal, 0);
    const revenueMesaPix = periodMesaBillings.filter(b => b.paymentMethod === 'pix').reduce((sum, b) => sum + b.valorTotal, 0);
    const revenueMesaTotal = revenueMesaDinheiro + revenueMesaPix;
    
    const revenueJukeboxDinheiro = periodJukeboxBillings.filter(b => b.paymentMethod === 'dinheiro').reduce((sum, b) => sum + b.valorTotal, 0);
    const revenueJukeboxPix = periodJukeboxBillings.filter(b => b.paymentMethod === 'pix').reduce((sum, b) => sum + b.valorTotal, 0);
    const revenueJukeboxTotal = revenueJukeboxDinheiro + revenueJukeboxPix;

    // Detailed Grua Stats
    const revenueGruaPix = periodGruaBillings.reduce((sum, b) => sum + (b.recebimentoPix || 0), 0);
    const revenueGruaEspecie = periodGruaBillings.reduce((sum, b) => sum + (b.recebimentoEspecie || 0), 0);
    const totalAluguelPagoGrua = periodGruaBillings.reduce((sum, b) => sum + (b.aluguelValor || 0), 0);


    // Debt Generated by Equipment
    const debtGeneratedMesa = periodMesaBillings.filter(b => b.paymentMethod === 'fiado').reduce((sum, b) => sum + (b.parteFirma || 0) + (b.parteCliente || 0), 0);
    const debtGeneratedJukebox = periodJukeboxBillings.filter(b => b.paymentMethod === 'fiado').reduce((sum, b) => sum + (b.parteFirma || 0) + (b.parteCliente || 0), 0);
    
    const totalDebtPaymentsReceived = periodDebtPayments.reduce((sum, p) => sum + p.amountPaid, 0);
    const totalExpenses = periodExpenses.reduce((sum, e) => sum + e.amount, 0);
    
    return {
      revenueMesaDinheiro,
      revenueMesaPix,
      revenueMesaTotal,
      revenueJukeboxDinheiro,
      revenueJukeboxPix,
      revenueJukeboxTotal,
      revenueGruaPix,
      revenueGruaEspecie,
      totalAluguelPagoGrua,
      debtGeneratedMesa,
      debtGeneratedJukebox,
      totalDebtPaymentsReceived,
      totalExpenses,
      periodMesaBillings,
      periodJukeboxBillings,
      periodGruaBillings,
      periodDebtPayments,
      periodExpenses,
    };
  }, [billings, expenses, debtPayments, dateRange]);
  
  const printReport = useCallback((title: string, content: string) => {
    const startDate = dateRange.start ? new Date(dateRange.start + 'T00:00:00').toLocaleDateString('pt-BR') : 'Início';
    const endDate = dateRange.end ? new Date(dateRange.end + 'T00:00:00').toLocaleDateString('pt-BR') : 'Fim';
    const dateTitle = `${startDate} a ${endDate}`;

    const reportHtml = `
      <html>
        <head>
          <title>${title} - ${dateTitle}</title>
          <style>
            body { font-family: Arial, sans-serif; font-size: 10pt; color: #333; }
            @page { size: A4 landscape; margin: 15mm; }
            h1, h2 { text-align: center; }
            h1 { font-size: 16pt; }
            h2 { font-size: 12pt; margin-bottom: 20px; border-bottom: 1px solid #ccc; padding-bottom: 5px; }
            table { width: 100%; border-collapse: collapse; margin-bottom: 20px; font-size: 9pt; }
            th, td { border: 1px solid #ccc; padding: 4px; text-align: left; }
            th { background-color: #f2f2f2; font-weight: bold; }
            .currency { text-align: right; font-family: monospace; }
            .no-records { text-align: center; color: #777; font-style: italic; }
            tfoot td { font-weight: bold; border-top: 2px solid #333; }
          </style>
        </head>
        <body>
          <h1>Montanha Bilhar & Jukebox</h1>
          <h2>${title} - Período: ${dateTitle}</h2>
          ${content}
        </body>
      </html>
    `;
    const printWindow = window.open('', '', 'height=800,width=1200');
    if (printWindow) {
        printWindow.document.write(reportHtml);
        printWindow.document.close();
        printWindow.focus();
        printWindow.print();
    }
  }, [dateRange]);

  const handlePrintMesaReport = useCallback(() => {
    const data = stats.periodMesaBillings;
    const total = stats.revenueMesaTotal;
    const customerMap = new Map<string, Customer>(customers.map(c => [c.id, c]));

    const content = `
      <h3>Receitas - Mesas de Sinuca</h3>
      <table>
        <thead>
          <tr>
            <th>Data</th>
            <th>Cliente</th>
            <th>Cidade</th>
            <th class="currency">Rel. Ant.</th>
            <th class="currency">Rel. Atual</th>
            <th class="currency">Jogadas</th>
            <th>Recebido</th>
            <th class="currency">Valor (Firma)</th>
          </tr>
        </thead>
        <tbody>
          ${data.length > 0 ? data.map(b => {
            const customer = customerMap.get(b.customerId);
            const cidade = customer ? customer.cidade : 'N/A';
            const paymentMethodDisplay = b.paymentMethod === 'fiado' ? 'Fiado' : (b.paymentMethod === 'pix' ? 'PIX' : 'Dinheiro');
            return `
              <tr>
                <td>${new Date(b.settledAt).toLocaleDateString('pt-BR')}</td>
                <td>${b.customerName}</td>
                <td>${cidade}</td>
                <td class="currency">${b.relogioAnterior}</td>
                <td class="currency">${b.relogioAtual}</td>
                <td class="currency">${b.partidasJogadas}</td>
                <td>${paymentMethodDisplay}</td>
                <td class="currency">R$ ${b.valorTotal.toFixed(2)}</td>
              </tr>
            `}).join('') : '<tr><td colspan="8" class="no-records">Nenhuma cobrança no período.</td></tr>'}
        </tbody>
        <tfoot>
          <tr>
            <td colspan="7"><strong>Total Recebido (Caixa)</strong></td>
            <td class="currency"><strong>R$ ${total.toFixed(2)}</strong></td>
          </tr>
        </tfoot>
      </table>
    `;
    printReport('Relatório de Mesas de Sinuca', content);
  }, [stats, printReport, customers]);

  const handlePrintJukeboxReport = useCallback(() => {
    const data = stats.periodJukeboxBillings;
    const total = stats.revenueJukeboxTotal;
    const customerMap = new Map<string, Customer>(customers.map(c => [c.id, c]));

    const content = `
      <h3>Receitas - Jukebox</h3>
      <table>
        <thead>
          <tr>
            <th>Data</th>
            <th>Cliente</th>
            <th>Cidade</th>
            <th class="currency">Rel. Ant.</th>
            <th class="currency">Rel. Atual</th>
            <th class="currency">Jogadas</th>
            <th>Pgto</th>
            <th class="currency">Valor (Firma)</th>
          </tr>
        </thead>
        <tbody>
          ${data.length > 0 ? data.map(b => {
            const customer = customerMap.get(b.customerId);
            const cidade = customer ? customer.cidade : 'N/A';
            return `
              <tr>
                <td>${new Date(b.settledAt).toLocaleDateString('pt-BR')}</td>
                <td>${b.customerName}</td>
                <td>${cidade}</td>
                <td class="currency">${b.relogioAnterior}</td>
                <td class="currency">${b.relogioAtual}</td>
                <td class="currency">${b.partidasJogadas}</td>
                <td>${b.paymentMethod}</td>
                <td class="currency">R$ ${b.valorTotal.toFixed(2)}</td>
              </tr>
            `}).join('') : '<tr><td colspan="8" class="no-records">Nenhuma cobrança no período.</td></tr>'}
        </tbody>
        <tfoot>
          <tr>
            <td colspan="7"><strong>Total Recebido (Caixa)</strong></td>
            <td class="currency"><strong>R$ ${total.toFixed(2)}</strong></td>
          </tr>
        </tfoot>
      </table>
    `;
    printReport('Relatório de Jukebox', content);
  }, [stats, printReport, customers]);
  
  const handlePrintGruaReport = useCallback(() => {
    const data = stats.periodGruaBillings;
    const customerMap = new Map<string, Customer>(customers.map(c => [c.id, c]));

    const totalSaldoBruto = data.reduce((sum, b) => sum + (b.saldo || 0), 0);
    const totalAluguelCliente = data.reduce((sum, b) => sum + (b.aluguelValor || 0), 0);
    const totalValorFirma = data.reduce((sum, b) => sum + b.valorTotal, 0);
    
    const content = `
      <h3>Receitas - Gruas de Pelúcia</h3>
      <table>
        <thead>
          <tr>
            <th>Data</th>
            <th>Cliente</th>
            <th>Cidade</th>
            <th>Grua Nº</th>
            <th class="currency">Rel. Ant.</th>
            <th class="currency">Rel. Atual</th>
            <th class="currency">Saldo Bruto</th>
            <th class="currency">Aluguel (Cliente)</th>
            <th class="currency">Valor (Firma)</th>
            <th class="currency">Reposição Pelúcia</th>
            <th class="currency">Receb. Espécie</th>
            <th class="currency">Receb. PIX</th>
          </tr>
        </thead>
        <tbody>
          ${data.length > 0 ? data.map(b => {
            const customer = customerMap.get(b.customerId);
            const cidade = customer ? customer.cidade : 'N/A';
            return `
            <tr>
              <td>${new Date(b.settledAt).toLocaleDateString('pt-BR')}</td>
              <td>${b.customerName}</td>
              <td>${cidade}</td>
              <td>${b.equipmentNumero}</td>
              <td class="currency">${b.relogioAnterior}</td>
              <td class="currency">${b.relogioAtual}</td>
              <td class="currency">R$ ${(b.saldo || 0).toFixed(2)}</td>
              <td class="currency">R$ ${(b.aluguelValor || 0).toFixed(2)}</td>
              <td class="currency">R$ ${b.valorTotal.toFixed(2)}</td>
              <td class="currency">${b.reposicaoPelucia || 0}</td>
              <td class="currency">R$ ${(b.recebimentoEspecie || 0).toFixed(2)}</td>
              <td class="currency">R$ ${(b.recebimentoPix || 0).toFixed(2)}</td>
            </tr>
          `}).join('') : '<tr><td colspan="12" class="no-records">Nenhuma cobrança de grua no período.</td></tr>'}
        </tbody>
        <tfoot>
          <tr>
            <td colspan="6"><strong>TOTAIS</strong></td>
            <td class="currency"><strong>R$ ${totalSaldoBruto.toFixed(2)}</strong></td>
            <td class="currency"><strong>R$ ${totalAluguelCliente.toFixed(2)}</strong></td>
            <td class="currency"><strong>R$ ${totalValorFirma.toFixed(2)}</strong></td>
            <td colspan="3"></td>
          </tr>
        </tfoot>
      </table>
    `;
    printReport('Relatório de Gruas de Pelúcia', content);
  }, [stats, printReport, customers]);

  const handlePrintDebtReport = useCallback(() => {
    const content = `
      <table>
        <thead><tr><th>Data</th><th>Cliente</th><th>Pgto</th><th class="currency">Valor Pago</th></tr></thead>
        <tbody>
          ${stats.periodDebtPayments.length > 0 ? stats.periodDebtPayments.map(p => `
            <tr>
              <td>${new Date(p.paidAt).toLocaleDateString('pt-BR')}</td>
              <td>${p.customerName}</td>
              <td>${p.paymentMethod}</td>
              <td class="currency">R$ ${p.amountPaid.toFixed(2)}</td>
            </tr>
          `).join('') : '<tr><td colspan="4" class="no-records">Nenhum pagamento de dívida no período.</td></tr>'}
        </tbody>
        <tfoot>
          <tr>
            <td colspan="3"><strong>Total Recebido</strong></td>
            <td class="currency"><strong>R$ ${stats.totalDebtPaymentsReceived.toFixed(2)}</strong></td>
          </tr>
        </tfoot>
      </table>
    `;
    printReport('Relatório de Pagamento de Dívidas', content);
  }, [stats, printReport]);

  const handlePrintExpenseReport = useCallback(() => {
    const content = `
      <table>
        <thead><tr><th>Data</th><th>Descrição</th><th class="currency">Valor</th></tr></thead>
        <tbody>
          ${stats.periodExpenses.length > 0 ? stats.periodExpenses.map(e => `
            <tr>
              <td>${new Date(e.date).toLocaleDateString('pt-BR')}</td>
              <td>${e.description}</td>
              <td class="currency">R$ ${e.amount.toFixed(2)}</td>
            </tr>
          `).join('') : '<tr><td colspan="3" class="no-records">Nenhuma despesa no período.</td></tr>'}
        </tbody>
        <tfoot>
          <tr>
            <td colspan="2"><strong>Total de Despesas</strong></td>
            <td class="currency"><strong>R$ ${stats.totalExpenses.toFixed(2)}</strong></td>
          </tr>
        </tfoot>
      </table>
    `;
    printReport('Relatório de Despesas', content);
  }, [stats, printReport]);

  const PrintButton = ({ onClick, label }: { onClick: () => void, label: string }) => (
     <div className="mt-4 pt-4 border-t border-slate-200 dark:border-slate-700/50">
        <button
            onClick={onClick}
            className="w-full inline-flex items-center justify-center gap-2 bg-cyan-600 text-white font-bold py-2 px-3 rounded-md hover:bg-cyan-500 transition-colors"
        >
            <PrinterIcon className="w-4 h-4" />
            <span>{label}</span>
        </button>
    </div>
  );

  return (
    <div className="max-w-6xl mx-auto">
      <PageHeader 
        title="Relatórios"
        subtitle="Análise detalhada do desempenho financeiro."
      />
      
      <div className="bg-white dark:bg-slate-800 p-4 rounded-lg shadow-lg border border-slate-200 dark:border-slate-700 mb-8 flex flex-wrap items-center gap-4">
        <h3 className="text-lg font-semibold text-slate-900 dark:text-white">Selecione o Período:</h3>
        <input name="start" type="date" value={dateRange.start} onChange={handleDateChange} className="bg-slate-100 dark:bg-slate-700 border border-slate-300 dark:border-slate-600 rounded-md py-2 px-3 text-slate-900 dark:text-white focus:outline-none focus:ring-2 focus:ring-emerald-500" />
        <span className="text-slate-500 dark:text-slate-400">até</span>
        <input name="end" type="date" value={dateRange.end} onChange={handleDateChange} className="bg-slate-100 dark:bg-slate-700 border border-slate-300 dark:border-slate-600 rounded-md py-2 px-3 text-slate-900 dark:text-white focus:outline-none focus:ring-2 focus:ring-emerald-500" />
      </div>

      <div className="grid grid-cols-1 lg:grid-cols-2 gap-8">
        <InfoCard title="Desempenho: Mesas de Sinuca">
            <InfoRow label="Receita (Dinheiro)" value={`R$ ${stats.revenueMesaDinheiro.toFixed(2)}`} valueColor="text-sky-600 dark:text-sky-400" />
            <InfoRow label="Receita PIX/Crédito" value={`R$ ${stats.revenueMesaPix.toFixed(2)}`} valueColor="text-emerald-600 dark:text-emerald-400" />
            <InfoRow label="Débito Gerado (Fiado)" value={`R$ ${stats.debtGeneratedMesa.toFixed(2)}`} valueColor="text-amber-600 dark:text-amber-400" />
            <div className="pt-3 mt-2 border-t border-slate-200 dark:border-slate-700/50">
                <InfoRow label="Total (Caixa)" value={`R$ ${stats.revenueMesaTotal.toFixed(2)}`} valueColor="text-green-600 dark:text-green-400 text-lg" />
            </div>
            <PrintButton onClick={handlePrintMesaReport} label="Imprimir Relatório de Mesas" />
        </InfoCard>

        <InfoCard title="Desempenho: Jukebox">
            <InfoRow label="Receita (Dinheiro)" value={`R$ ${stats.revenueJukeboxDinheiro.toFixed(2)}`} valueColor="text-sky-600 dark:text-sky-400" />
            <InfoRow label="Receita PIX/Crédito" value={`R$ ${stats.revenueJukeboxPix.toFixed(2)}`} valueColor="text-emerald-600 dark:text-emerald-400" />
            <InfoRow label="Débito Gerado (Fiado)" value={`R$ ${stats.debtGeneratedJukebox.toFixed(2)}`} valueColor="text-amber-600 dark:text-amber-400" />
            <div className="pt-3 mt-2 border-t border-slate-200 dark:border-slate-700/50">
                <InfoRow label="Total (Caixa)" value={`R$ ${stats.revenueJukeboxTotal.toFixed(2)}`} valueColor="text-green-600 dark:text-green-400 text-lg" />
            </div>
            <PrintButton onClick={handlePrintJukeboxReport} label="Imprimir Relatório de Jukebox" />
        </InfoCard>

         <InfoCard title="Desempenho: Gruas">
            <InfoRow label="Receita (Dinheiro)" value={`R$ ${stats.revenueGruaEspecie.toFixed(2)}`} valueColor="text-sky-600 dark:text-sky-400" />
            <InfoRow label="Receita (PIX)" value={`R$ ${stats.revenueGruaPix.toFixed(2)}`} valueColor="text-emerald-600 dark:text-emerald-400" />
            <InfoRow label="Aluguel Pago (p/ Cliente)" value={`R$ ${stats.totalAluguelPagoGrua.toFixed(2)}`} valueColor="text-amber-600 dark:text-amber-400" />
            <PrintButton onClick={handlePrintGruaReport} label="Imprimir Relatório de Gruas" />
        </InfoCard>

        <InfoCard title="Pagamentos de Dívidas">
            <InfoRow label="Total Recebido" value={`R$ ${stats.totalDebtPaymentsReceived.toFixed(2)}`} valueColor="text-green-600 dark:text-green-400" />
             <PrintButton onClick={handlePrintDebtReport} label="Imprimir Relatório de Dívidas" />
        </InfoCard>
        
        <InfoCard title="Despesas do Período">
            <InfoRow label="Total Gasto" value={`R$ ${stats.totalExpenses.toFixed(2)}`} valueColor="text-red-600 dark:text-red-400" />
            <PrintButton onClick={handlePrintExpenseReport} label="Imprimir Relatório de Despesas" />
        </InfoCard>
      </div>
    </div>
  );
};

export default RelatoriosView;