// views/RelatoriosView.tsx
import React, { useState, useMemo, useCallback } from 'react';
import { Billing, Customer, DebtPayment, Expense } from '../types';
import PageHeader from '../components/PageHeader';
import { PrinterIcon } from '../components/icons/PrinterIcon';

interface RelatoriosViewProps {
  customers: Customer[];
  billings: Billing[];
  expenses: Expense[];
  debtPayments: DebtPayment[];
}

// --- Sub-components (moved outside for performance and best practices) ---

interface InfoCardProps {
    title: string;
    children: React.ReactNode;
}
const InfoCard: React.FC<InfoCardProps> = React.memo(({ title, children }) => (
    <div className="bg-slate-800 p-6 rounded-lg shadow-lg border border-slate-700 h-full flex flex-col">
        <h3 className="text-xl font-semibold text-white mb-4 border-b border-slate-700 pb-3">{title}</h3>
        <div className="flex-grow">
            <dl className="space-y-3">
                {children}
            </dl>
        </div>
    </div>
));

interface InfoRowProps {
    label: string;
    value: string;
    valueColor?: string;
}
const InfoRow: React.FC<InfoRowProps> = React.memo(({ label, value, valueColor = 'text-slate-300' }) => (
    <div className="flex justify-between items-baseline">
        <dt className="text-slate-400">{label}</dt>
        <dd className={`font-mono font-bold ${valueColor}`}>{value}</dd>
    </div>
));

// --- Main View Component ---

const RelatoriosView: React.FC<RelatoriosViewProps> = ({ customers, billings, expenses, debtPayments }) => {
  const [currentDate, setCurrentDate] = useState(new Date());

  const handleMonthChange = useCallback((month: number) => {
    setCurrentDate(prevDate => new Date(prevDate.getFullYear(), month, 1));
  }, []);

  const handleYearChange = useCallback((year: number) => {
    setCurrentDate(prevDate => new Date(year, prevDate.getMonth(), 1));
  }, []);

  const stats = useMemo(() => {
    const year = currentDate.getFullYear();
    const month = currentDate.getMonth();

    const monthlyBillings = billings.filter(b => {
      const date = new Date(b.settledAt);
      return date.getFullYear() === year && date.getMonth() === month;
    });

    const monthlyDebtPayments = debtPayments.filter(p => {
      const date = new Date(p.paidAt);
      return date.getFullYear() === year && date.getMonth() === month;
    });

    const monthlyExpenses = expenses.filter(e => {
      const date = new Date(e.date);
      return date.getFullYear() === year && date.getMonth() === month;
    });
    
    // Filtered Billings
    const monthlyMesaBillings = monthlyBillings.filter(b => b.equipmentType === 'mesa');
    const monthlyJukeboxBillings = monthlyBillings.filter(b => b.equipmentType === 'jukebox');
    const monthlyGruaBillings = monthlyBillings.filter(b => b.equipmentType === 'grua');

    // Revenue by Equipment (Cash Box)
    const revenueMesa = monthlyMesaBillings.filter(b => b.paymentMethod !== 'fiado').reduce((sum, b) => sum + b.valorTotal, 0);
    const revenueJukebox = monthlyJukeboxBillings.filter(b => b.paymentMethod !== 'fiado').reduce((sum, b) => sum + b.valorTotal, 0);
    
    // Detailed Grua Stats
    const revenueGruaPix = monthlyGruaBillings.reduce((sum, b) => sum + (b.recebimentoPix || 0), 0);
    const revenueGruaEspecie = monthlyGruaBillings.reduce((sum, b) => sum + (b.recebimentoEspecie || 0), 0);
    const totalAluguelPagoGrua = monthlyGruaBillings.reduce((sum, b) => sum + (b.aluguelValor || 0), 0);


    // Debt Generated by Equipment
    const debtGeneratedMesa = monthlyMesaBillings.filter(b => b.paymentMethod === 'fiado').reduce((sum, b) => sum + (b.parteFirma || 0) + (b.parteCliente || 0), 0);
    const debtGeneratedJukebox = monthlyJukeboxBillings.filter(b => b.paymentMethod === 'fiado').reduce((sum, b) => sum + (b.parteFirma || 0) + (b.parteCliente || 0), 0);
    
    const totalDebtPaymentsReceived = monthlyDebtPayments.reduce((sum, p) => sum + p.amountPaid, 0);
    const totalExpenses = monthlyExpenses.reduce((sum, e) => sum + e.amount, 0);
    
    return {
      revenueMesa,
      revenueJukebox,
      revenueGruaPix,
      revenueGruaEspecie,
      totalAluguelPagoGrua,
      debtGeneratedMesa,
      debtGeneratedJukebox,
      totalDebtPaymentsReceived,
      totalExpenses,
      monthlyMesaBillings,
      monthlyJukeboxBillings,
      monthlyGruaBillings,
      monthlyDebtPayments,
      monthlyExpenses,
    };
  }, [billings, expenses, debtPayments, currentDate]);

  const monthNames = ["Janeiro", "Fevereiro", "Março", "Abril", "Maio", "Junho", "Julho", "Agosto", "Setembro", "Outubro", "Novembro", "Dezembro"];
  const currentYear = new Date().getFullYear();
  const years = Array.from({ length: 5 }, (_, i) => currentYear - i);
  
  const printReport = useCallback((title: string, content: string) => {
    const reportHtml = `
      <html>
        <head>
          <title>${title} - ${monthNames[currentDate.getMonth()]}/${currentDate.getFullYear()}</title>
          <style>
            body { font-family: Arial, sans-serif; font-size: 10pt; color: #333; }
            @page { size: A4 landscape; margin: 15mm; }
            h1, h2 { text-align: center; }
            h1 { font-size: 16pt; }
            h2 { font-size: 12pt; margin-bottom: 20px; border-bottom: 1px solid #ccc; padding-bottom: 5px; }
            table { width: 100%; border-collapse: collapse; margin-bottom: 20px; font-size: 9pt; }
            th, td { border: 1px solid #ccc; padding: 4px; text-align: left; }
            th { background-color: #f2f2f2; font-weight: bold; }
            .currency { text-align: right; font-family: monospace; }
            .no-records { text-align: center; color: #777; font-style: italic; }
            tfoot td { font-weight: bold; border-top: 2px solid #333; }
          </style>
        </head>
        <body>
          <h1>Montanha Bilhar & Jukebox</h1>
          <h2>${title} - ${monthNames[currentDate.getMonth()]} de ${currentDate.getFullYear()}</h2>
          ${content}
        </body>
      </html>
    `;
    const printWindow = window.open('', '', 'height=800,width=1200');
    if (printWindow) {
        printWindow.document.write(reportHtml);
        printWindow.document.close();
        printWindow.focus();
        printWindow.print();
    }
  }, [currentDate, monthNames]);

  const generateBillingTable = (title: string, data: Billing[], total: number) => `
    <h3>${title}</h3>
    <table>
      <thead><tr><th>Data</th><th>Cliente</th><th>Pgto</th><th class="currency">Valor (Firma)</th></tr></thead>
      <tbody>
        ${data.length > 0 ? data.map(b => `
          <tr>
            <td>${new Date(b.settledAt).toLocaleDateString('pt-BR')}</td>
            <td>${b.customerName}</td>
            <td>${b.paymentMethod}</td>
            <td class="currency">R$ ${b.valorTotal.toFixed(2)}</td>
          </tr>
        `).join('') : '<tr><td colspan="4" class="no-records">Nenhuma cobrança no período.</td></tr>'}
      </tbody>
      <tfoot>
        <tr>
          <td colspan="3"><strong>Total Recebido (Caixa)</strong></td>
          <td class="currency"><strong>R$ ${total.toFixed(2)}</strong></td>
        </tr>
      </tfoot>
    </table>
  `;

  const handlePrintMesaReport = useCallback(() => {
    const content = generateBillingTable('Receitas - Mesas de Sinuca', stats.monthlyMesaBillings, stats.revenueMesa);
    printReport('Relatório de Mesas de Sinuca', content);
  }, [stats, printReport, generateBillingTable]);

  const handlePrintJukeboxReport = useCallback(() => {
    const content = generateBillingTable('Receitas - Jukebox', stats.monthlyJukeboxBillings, stats.revenueJukebox);
    printReport('Relatório de Jukebox', content);
  }, [stats, printReport, generateBillingTable]);
  
  const handlePrintGruaReport = useCallback(() => {
    const data = stats.monthlyGruaBillings;
    // FIX: Explicitly type the Map to ensure correct type inference for `customer`.
    const customerMap = new Map<string, Customer>(customers.map(c => [c.id, c]));

    const totalSaldoBruto = data.reduce((sum, b) => sum + (b.saldo || 0), 0);
    const totalAluguelCliente = data.reduce((sum, b) => sum + (b.aluguelValor || 0), 0);
    const totalValorFirma = data.reduce((sum, b) => sum + b.valorTotal, 0);
    
    const content = `
      <h3>Receitas - Gruas de Pelúcia</h3>
      <table>
        <thead>
          <tr>
            <th>Data</th>
            <th>Cliente</th>
            <th>Cidade</th>
            <th>Grua Nº</th>
            <th class="currency">Saldo Bruto</th>
            <th class="currency">Aluguel (Cliente)</th>
            <th class="currency">Valor (Firma)</th>
            <th class="currency">Reposição Pelúcia</th>
            <th class="currency">Receb. Espécie</th>
            <th class="currency">Receb. PIX</th>
          </tr>
        </thead>
        <tbody>
          ${data.length > 0 ? data.map(b => {
            const customer = customerMap.get(b.customerId);
            const cidade = customer ? customer.cidade : 'N/A';
            return `
            <tr>
              <td>${new Date(b.settledAt).toLocaleDateString('pt-BR')}</td>
              <td>${b.customerName}</td>
              <td>${cidade}</td>
              <td>${b.equipmentNumero}</td>
              <td class="currency">R$ ${(b.saldo || 0).toFixed(2)}</td>
              <td class="currency">R$ ${(b.aluguelValor || 0).toFixed(2)}</td>
              <td class="currency">R$ ${b.valorTotal.toFixed(2)}</td>
              <td class="currency">${b.reposicaoPelucia || 0}</td>
              <td class="currency">R$ ${(b.recebimentoEspecie || 0).toFixed(2)}</td>
              <td class="currency">R$ ${(b.recebimentoPix || 0).toFixed(2)}</td>
            </tr>
          `}).join('') : '<tr><td colspan="10" class="no-records">Nenhuma cobrança de grua no período.</td></tr>'}
        </tbody>
        <tfoot>
          <tr>
            <td colspan="4"><strong>TOTAIS</strong></td>
            <td class="currency"><strong>R$ ${totalSaldoBruto.toFixed(2)}</strong></td>
            <td class="currency"><strong>R$ ${totalAluguelCliente.toFixed(2)}</strong></td>
            <td class="currency"><strong>R$ ${totalValorFirma.toFixed(2)}</strong></td>
            <td colspan="3"></td>
          </tr>
        </tfoot>
      </table>
    `;
    printReport('Relatório de Gruas de Pelúcia', content);
  }, [stats, printReport, customers]);

  const handlePrintDebtReport = useCallback(() => {
    const content = `
      <table>
        <thead><tr><th>Data</th><th>Cliente</th><th>Pgto</th><th class="currency">Valor Pago</th></tr></thead>
        <tbody>
          ${stats.monthlyDebtPayments.length > 0 ? stats.monthlyDebtPayments.map(p => `
            <tr>
              <td>${new Date(p.paidAt).toLocaleDateString('pt-BR')}</td>
              <td>${p.customerName}</td>
              <td>${p.paymentMethod}</td>
              <td class="currency">R$ ${p.amountPaid.toFixed(2)}</td>
            </tr>
          `).join('') : '<tr><td colspan="4" class="no-records">Nenhum pagamento de dívida no período.</td></tr>'}
        </tbody>
        <tfoot>
          <tr>
            <td colspan="3"><strong>Total Recebido</strong></td>
            <td class="currency"><strong>R$ ${stats.totalDebtPaymentsReceived.toFixed(2)}</strong></td>
          </tr>
        </tfoot>
      </table>
    `;
    printReport('Relatório de Pagamento de Dívidas', content);
  }, [stats, printReport]);

  const handlePrintExpenseReport = useCallback(() => {
    const content = `
      <table>
        <thead><tr><th>Data</th><th>Descrição</th><th class="currency">Valor</th></tr></thead>
        <tbody>
          ${stats.monthlyExpenses.length > 0 ? stats.monthlyExpenses.map(e => `
            <tr>
              <td>${new Date(e.date).toLocaleDateString('pt-BR')}</td>
              <td>${e.description}</td>
              <td class="currency">R$ ${e.amount.toFixed(2)}</td>
            </tr>
          `).join('') : '<tr><td colspan="3" class="no-records">Nenhuma despesa no período.</td></tr>'}
        </tbody>
        <tfoot>
          <tr>
            <td colspan="2"><strong>Total de Despesas</strong></td>
            <td class="currency"><strong>R$ ${stats.totalExpenses.toFixed(2)}</strong></td>
          </tr>
        </tfoot>
      </table>
    `;
    printReport('Relatório de Despesas', content);
  }, [stats, printReport]);

  const PrintButton = ({ onClick, label }: { onClick: () => void, label: string }) => (
     <div className="mt-4 pt-4 border-t border-slate-700/50">
        <button
            onClick={onClick}
            className="w-full inline-flex items-center justify-center gap-2 bg-cyan-600 text-white font-bold py-2 px-3 rounded-md hover:bg-cyan-500 transition-colors"
        >
            <PrinterIcon className="w-4 h-4" />
            <span>{label}</span>
        </button>
    </div>
  );

  return (
    <div className="max-w-6xl mx-auto">
      <PageHeader 
        title="Relatórios"
        subtitle="Análise detalhada do desempenho financeiro."
      />
      
      <div className="bg-slate-800 p-4 rounded-lg shadow-lg border border-slate-700 mb-8 flex flex-wrap items-center gap-4">
        <h3 className="text-lg font-semibold text-white">Selecione o Período:</h3>
        <select value={currentDate.getMonth()} onChange={(e) => handleMonthChange(parseInt(e.target.value))} className="bg-slate-700 border border-slate-600 rounded-md py-2 px-3 text-white focus:outline-none focus:ring-2 focus:ring-emerald-500">
          {monthNames.map((month, index) => <option key={month} value={index}>{month}</option>)}
        </select>
        <select value={currentDate.getFullYear()} onChange={(e) => handleYearChange(parseInt(e.target.value))} className="bg-slate-700 border border-slate-600 rounded-md py-2 px-3 text-white focus:outline-none focus:ring-2 focus:ring-emerald-500">
           {years.map(year => <option key={year} value={year}>{year}</option>)}
        </select>
      </div>

      <div className="grid grid-cols-1 lg:grid-cols-2 gap-8">
        <InfoCard title="Desempenho: Mesas de Sinuca">
            <InfoRow label="Receita (Caixa)" value={`R$ ${stats.revenueMesa.toFixed(2)}`} valueColor="text-emerald-400" />
            <InfoRow label="Débito Gerado (Fiado)" value={`R$ ${stats.debtGeneratedMesa.toFixed(2)}`} valueColor="text-amber-400" />
            <PrintButton onClick={handlePrintMesaReport} label="Imprimir Relatório de Mesas" />
        </InfoCard>

        <InfoCard title="Desempenho: Jukebox">
            <InfoRow label="Receita (Caixa)" value={`R$ ${stats.revenueJukebox.toFixed(2)}`} valueColor="text-emerald-400" />
            <InfoRow label="Débito Gerado (Fiado)" value={`R$ ${stats.debtGeneratedJukebox.toFixed(2)}`} valueColor="text-amber-400" />
            <PrintButton onClick={handlePrintJukeboxReport} label="Imprimir Relatório de Jukebox" />
        </InfoCard>

         <InfoCard title="Desempenho: Gruas">
            <InfoRow label="Receita (Dinheiro)" value={`R$ ${stats.revenueGruaEspecie.toFixed(2)}`} valueColor="text-sky-400" />
            <InfoRow label="Receita (PIX)" value={`R$ ${stats.revenueGruaPix.toFixed(2)}`} valueColor="text-emerald-400" />
            <InfoRow label="Aluguel Pago (p/ Cliente)" value={`R$ ${stats.totalAluguelPagoGrua.toFixed(2)}`} valueColor="text-amber-400" />
            <PrintButton onClick={handlePrintGruaReport} label="Imprimir Relatório de Gruas" />
        </InfoCard>

        <InfoCard title="Pagamentos de Dívidas">
            <InfoRow label="Total Recebido" value={`R$ ${stats.totalDebtPaymentsReceived.toFixed(2)}`} valueColor="text-green-400" />
             <PrintButton onClick={handlePrintDebtReport} label="Imprimir Relatório de Dívidas" />
        </InfoCard>
        
        <InfoCard title="Despesas do Período">
            <InfoRow label="Total Gasto" value={`R$ ${stats.totalExpenses.toFixed(2)}`} valueColor="text-red-400" />
            <PrintButton onClick={handlePrintExpenseReport} label="Imprimir Relatório de Despesas" />
        </InfoCard>
      </div>
    </div>
  );
};

export default RelatoriosView;
